name: Deploy Frontend
on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  build:
    name: Build and run docker
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Docker login
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Docker build
        run: docker build -t kp27docker/react-test -f Dockerfile.dev .
      
      - name: Docker run
        run: docker run -e CI=true kp27docker/react-test npm test
