name: Deploy Frontend
on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  build:
    name: Build and run docker
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Docker login
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Docker build
        run: docker build -t kp27docker/react-test -f Dockerfile.dev .
      
      - name: Docker run
        run: docker run -e CI=true kp27docker/react-test npm test

      - name: Generate deployment package
        run: zip -r deploy.zip . -x '*.git*'

      - name: Deploy to Elastic Beanstalk
        uses: einaregilsson/beanstalk-deploy@v18
        with:
          aws_access_key: ${{ secrets.AWS_BS_ACCESS_KEY }}
          aws_secret_key: ${{ secrets. AWS_BS_SECRET_KEY }}
          application_name: docker-gh
          environment_name: Frontend-env
          existing_bucket_name: elasticbeanstalk-eu-north-1-147704599131
          region: eu-north-1
          version_label: ${{ github.sha }}
          deployment_package: deploy.zip
